# Site settings
title: Aaron Nwabuoku
email: aaron.nwabuoku@herzberglabs.com
description: Software developer with 4+ years hands-on working experience in fullstack Web and Android mobile development.
twitter_username: aerovulpe
github_username: aerovulpe
linkedin_username: aerovulpe

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
